# Generated by Django 2.2.15 on 2020-08-25 14:51

import build_migration.todo.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(max_length=255, upload_to=build_migration.todo.models.get_attachment_upload_dir)),
            ],
            options={
                'db_table': 'todo_attachment',
                'managed': False,
            },
        ),
    ]
