# Generated by Django 2.2.15 on 2020-08-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='extra_field',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
