# Generated by Django 2.2.15 on 2020-08-26 09:12

import build_migration.todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file',
            new_name='file_object',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_object',
            field=models.FileField(db_column='file', max_length=255, upload_to=build_migration.todo.models.get_attachment_upload_dir),
        ),
    ]
